CREATE TABLE ESCREVEU (
    FK_USUARIO_cpf CHAR(11),
    FK_AUTOR_guid CHAR(36),
    PRIMARY KEY (FK_USUARIO_cpf, FK_AUTOR_guid),
    FOREIGN KEY (FK_USUARIO_cpf) REFERENCES USUARIO(cpf),
    FOREIGN KEY (FK_AUTOR_guid) REFERENCES AUTOR(guid)
);