CREATE TABLE ESCREVEU (
    FK_LIVRO_cpf CHAR(11),
    FK_AUTOR_guid CHAR(36),
    PRIMARY KEY (FK_LIVRO_cpf, FK_AUTOR_guid),
    FOREIGN KEY (FK_LIVRO_cpf) REFERENCES LIVRO(guid),
    FOREIGN KEY (FK_AUTOR_guid) REFERENCES AUTOR(guid)
);  