CREATE TABLE ESCREVEU (
    FK_LIVRO_guid CHAR(11),
    FK_AUTOR_guid CHAR(36),
    PRIMARY KEY (FK_LIVRO_guid, FK_AUTOR_guid),
    FOREIGN KEY (FK_LIVRO_guid) REFERENCES LIVRO(guid),
    FOREIGN KEY (FK_AUTOR_guid) REFERENCES AUTOR(guid)
);  